### PR TITLE
ISLANDORA-2534; SUP-5934. Resolve PHP warnings when array keys don't exist

### PR DESCRIPTION
**Pull request by nhart**
**JIRA Ticket**: [(link)](https://islandora-legacy.atlassian.net/browse/ISLANDORA-2534)

# What does this Pull Request do?

Adds checks to verify array key exists before trying to reference it.

# How should this be tested?
Enable Islandora Solr Metadata for display, add a content model and setup fields leaving the description field empty.
View an object that uses the profile set up above.
Verify no errors are thrown

# Interested parties
@patdunlavey  @Islandora/legacy-committers

### CODE REVIEW

**Comment by whikloj** [comment]
I don't use this module, but I can't see this causing any more problems than it would solve.

**Review by MorganDawe — APPROVED** [review]

**Comment by nhart** [comment]
@whikloj  can you merge this please?

**Comment by nchiasson-dgi** [comment]
I have tested this locally with @nhart and the messages infact do go away when fix is applied. Field is still functional as intended after fix has been applied as well.

**Comment by whikloj** [comment]
I have no rights to the islandora-legacy jira, so I can't close the linked ticket. If you could that would be great @nhart

**Comment by nhart** [comment]
Thank you @whikloj, much appreciated. I've closed the Jira ticket.

**Pull request merged**
