### PR TITLE
Address ISLANDORA-1771; Check multivalued fields for empties when omi…

### PR DESCRIPTION
**Pull request by nhart**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1771
# What does this Pull Request do?

The PR makes "omit empty values" work on multivalued fields where all values are empty.
# How should this be tested?

Follow the steps to re-produce in the Jira ticket.
# Additional Notes:
- Does this change require documentation to be updated?  No
- Does this change add any new dependencies? No
- Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? No
- Could this change impact execution of existing code? No
# Interested parties

@jordandukart and @Islandora/7-x-1-x-committers as maintainer is a colleague.

### CODE REVIEW

**Comment by jordandukart** [comment]
This looks good from my end, can another @Islandora/7-x-1-x-committers please look at this?

**Comment by DiegoPino** [comment]
@jordandukart and @nhart will check today.

**Comment by nhart** [comment]
@DiegoPino have you had a chance to review this yet? Any other @Islandora/7-x-1-x-committers want to look at this? The 24 hours have passed.

**Comment by DiegoPino** [comment]
@nhart sorry, very sick last week. Looks fine. Merging now

**Comment by nhart** [comment]
Thanks @DiegoPino  Feel better!

**Pull request merged**
